extensions:
  health_check:
    endpoint: 127.0.0.1:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector-metrics
          scrape_interval: 10s
          static_configs:
            - targets: ["127.0.0.1:8888"]
        - job_name: grafana-metrics
          scrape_interval: 10s
          static_configs:
            - targets: ["grafana:3000"]
  syslog:
    udp:
      listen_address: "0.0.0.0:54526"
    protocol: rfc5424
    location: Asia/Tokyo

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 10
  batch:
    send_batch_size: 8192
    timeout: 1s
    send_batch_max_size: 0
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: appname, hostname
  resource:
    attributes:
      - action: insert
        key: loki.format
        value: json

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    tls:
      insecure: true
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  debug:
    verbosity: detailed
    sampling_initial: 2
    sampling_thereafter: 200

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [memory_limiter, batch]
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp]
    logs:
      receivers: [syslog]
      processors: [memory_limiter, attributes, resource, batch]
      exporters: [loki]
  extensions: [health_check]
  telemetry:
    metrics:
      address: 127.0.0.1:8888
      level: detailed
    logs:
      level: debug
      encoding: json
